import json, os

result = {
    "Paper Name": "Multi-criteria optimal sizing and analysis of PV/wind/fuel cell/battery/diesel generator for rural electrification: A case study in Chad",
    "NOTES": "All component cost/efficiency values from Table 2. DG efficiency=80% (Table 2). CO2 emission factor for DG=2.7 kg/L (section 2.4.6). SOx=0.5 g/kWh, NOx=0.22 g/kWh, CO2=690 g/kWh (Table 3). rated_PV is per-unit (330 W, Table 2); optimal installed solar=493 kW (Table 5). N_PV=1494 (493 kW / 0.330 kW). N_WT=332 (166 kW / 0.5 kW). N_EL=67 (202 kW / 3 kW). N_FC=48 (144 kW / 3 kW). N_H2 tanks=997 (Table 5). N_DG=0 (DG not used in optimal solution). Fuel consumption coeffs: AG=0.246 L/kWh, BG=0.0845 L/kWh (section 2.4.6). Electrolyzer and FC O&M listed as 1400$/kW in Table 2 (likely annual $/kW/yr). H2_LHV=33.33 kWh/kg (section 2.4.7). Inverter O&M=0 (Table 2). Interest rate r=10% (section 2.5). Project lifetime=20 years (Table 2). LPSP=0% (LOLP=0 from Table 6). v_cut_in and v_rated not explicitly stated in paper. Cut-in/rated wind speeds not provided. off-grid system so p_grid not applicable (no grid connection). life_DG=43800 h (Table 2). Battery: 1.35 kWh per unit (Table 2); total charge energy=229180 kWh implies ~169763 units, but paper does not explicitly state N_Bat. Replacement costs not individually stated in the paper (likely included in annualized cost equations). Operating costs c_FC, c_DG, c_EL not stated separately (O&M captured as om_*). eta_WT=96% from Table 2 (this is the wind turbine converter/overall efficiency, not aerodynamic Cp).",
    "TOTAL ANNUAL LOAD DEMAND": "542390 kWh",
    "LCOE": "0.2982 $/kWh",
    "LPSP": "0%",
    "COE": "0.2982 $/kWh",
    "rated_PV": "330 W",
    "v_cut_in": null,
    "v_rated": null,
    "rated_power": "0.5 kW",
    "Cap_H2": "83874 kWh",
    "Cap_FC": "144 kW",
    "Cap_EL": "202 kW",
    "Cap_DG": "0 kW",
    "H_min_percentage": "5%",
    "H_max_percentage": "100%",
    "f_0": "0.246 L/kWh",
    "f_1": "0.0845 L/kWh",
    "eta_PV": "17.01%",
    "eta_FC": "50%",
    "eta_EL": "74%",
    "eta_INVT": "95%",
    "H2_LHV": "33.33 kWh/kg",
    "c_PV": "270 $",
    "c_WT": "2000 $",
    "c_H2": "2000 $",
    "c_FC_cap": "20000 $",
    "c_EL_cap": "20000 $",
    "c_DG_cap": "500 $",
    "c_INVT": "1500 $",
    "c_FC": null,
    "c_DG": null,
    "c_EL": null,
    "c_DG_FUEL": "1 $/L",
    "om_PV": "20 $/year",
    "om_WT": "60 $/year",
    "om_H2": "0 $/year",
    "om_FC": "1400 $/kW",
    "om_EL": "1400 $/kW",
    "om_DG": "0.10 $/hour",
    "om_INVT": "0 $/year",
    "rc_PV": null,
    "rc_WT": null,
    "rc_H2": null,
    "rc_FC": null,
    "rc_EL": null,
    "rc_DG": null,
    "rc_INVT": null,
    "e_FC": null,
    "e_DG": "2.7 kg/L",
    "e_EL": null,
    "T_life": "20 years",
    "r": "10%",
    "p_grid": null,
    "A_PV": null,
    "P_DG_min": null,
    "life_PV": "20 years",
    "life_WT": "20 years",
    "life_H2": "20 years",
    "life_FC": "5 years",
    "life_EL": "5 years",
    "life_DG": "43800 h",
    "life_INVT": "10 years",
    "N_PV": "1494",
    "N_WT": "332",
    "N_H2": "997",
    "N_FC": "48",
    "N_EL": "67",
    "N_DG": "0"
}

output_path = r"C:\Users\Admin\OneDrive\Desktop\jims\parameters_extraction\results\per_paper\60169-194014-4-PB.json"
os.makedirs(os.path.dirname(output_path), exist_ok=True)

with open(output_path, 'w') as f:
    json.dump(result, f, indent=2)

print(f"Written to {output_path}")
print(f"Keys: {len(result)}, True values: {sum(1 for v in result.values() if v is not None)}")
